name: ">_ Developer"
description: blogging about stuffs
meta_description: "Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
# domain_name: 'kgamage.com'
permalink: /:title
# google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
# url:            'blog url'
author:         'Harindu Dilshan'
disqus: true

# theme_skin: blue # blue turquoise green berry orange ceramic
